name: Deploy ejabberd to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  AWS_ECS_CLUSTER: uima
  AWS_ECS_SERVICE: ejabberd
  IMAGE_NAME: ejabberd/ecs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ env.AWS_ECS_CLUSTER }} \
            --service ${{ env.AWS_ECS_SERVICE }} \
            --force-new-deployment \
            --image ${{ env.IMAGE_NAME }}
