name: Build and deploy ejabberd container
on:
  push:
    branches:
      - master
jobs:
  docker:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dockeroo80/uima-ejabberd
          tags: latest
          registry: docker.io
          dockerfile: ./Dockerfile
          username: dockeroo80
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
